base_image: "anyscale/ray-ml:pinned-nightly-py38"
env_vars: {"RAY_grpc_based_resource_broadcast": "true"}
debian_packages: ["pssh"]

python:
  pip_packages: []
  conda_packages: []

post_build_cmds:
  - pip uninstall -y ray
  - pip3 install ray[all]@https://yic-data.s3.us-west-2.amazonaws.com/ray-2.0.0.dev0-cp38-cp38-linux_x86_64.whl
  - pip3 install sklearn
